name    'arusso-tomcat6'
version '0.0.4'
source 'https://github.com/arusso/puppet-tomcat6'
author 'arusso'
license 'MIT'
summary 'a tomcat6 module that supports multiple instances'
description 'a tomcat6 module that supports multiple instances'
project_page 'https://github.com/arusso/puppet-tomcat6'

dependency 'puppetlabs/stdlib', '>= 2.6.0'
